apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctf-platform
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: mariadb
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --wait_timeout=28800
            - --log-warnings=0
          env:
            - name: MARIADB_DATABASE
              value: ctfd
            - name: MARIADB_PASSWORD
              value: KHQV9Ab3HvmNY
            - name: MARIADB_ROOT_PASSWORD
              value: FNQQtp8
            - name: MARIADB_USER
              value: ctfd
          image: mariadb:10.5.12
          imagePullPolicy: ""
          name: mariadb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctf-platform
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb