apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git@gitlab.com:hu-hc/jcr/platform/ctfd-as-a-service.git/overlays/development/minimal

configMapGenerator:
- name: configmap-ctfd
  behavior: merge
  env: values.env