apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ctfd
  name: ctfd-uploads-claim
  namespace: ctf-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: ctf-platform
 labels:
    app: mariadb
 name: mariadb-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi