apiVersion: v1
kind: Service
metadata:
  name: ctfd-service
  namespace: ctf-platform
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: ctfd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd
  namespace: ctf-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: ctfd
    spec:
      imagePullSecrets:
        - name: gitlab-pull
      containers:
        - env:
            - name: ACCESS_LOG
              value: "-"
            - name: ERROR_LOG
              value: "-"
            - name: LOG_FOLDER
              value: /var/log/CTFd
            - name: UPLOAD_FOLDER
              value: /var/uploads
            - name: WORKERS
              value: "1"
            - name: SURF_CLIENT_ID
              value: ctfd.jointcyberrange.nl
            - name: SURF_CLIENT_SECRET
              value: MyMERqI8QPo7eYVlp6jF
          image: registry.gitlab.com/hu-hc/jcr/platform/ctf-platform/master:latest
          name: ctfd
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: ca-issuer
#   namespace: ctf-platform
# spec:
#   ca:
#     secretName: ca-key-pair
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: kubernetes-docker-internal
#   namespace: ctf-platform
# spec:
#   secretName: kubernetes-docker-internal-tls
#   issuerRef:
#     name: ca-issuer
#     kind: Issuer
#   commonName: kubernetes.docker.internal
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd-ingress
  namespace: ctf-platform
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - kubernetes.docker.internal
      secretName: kubernetes-docker-internal-tls
  rules:
    - host: "kubernetes.docker.internal"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: ctfd-service
                port:
                  number: 8000
